# -*- coding: utf-8 -*-
"""python_introduction_P1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FDSc9S4bepPV6a3m6_ZkSzf7fsvj8ipV

## Buatlah sebuah program yang:

   1. Meminta input dari pengguna:

       - Nama mahasiswa

       - NIM mahasiswa

       - Nilai ujian (dalam angka, 0–100)

   2. Cek dan tampilkan tipe data dari setiap input.

   3. Gunakan if-elif-else untuk menentukan kategori nilai, dengan kriteria sebagai berikut:
   
```
Nilai | Kategori
85 - 100 | A (Sangat Baik)
75 - 84 | B (Baik)
60 - 74 | C (Cukup)
40 - 59 | D (Kurang)
< 40 | E (Sangat Kurang)
```

```
==== Ekspektasi Output Jawaban : =====
Masukkan nama mahasiswa: Sarah
Masukkan NIM: 12345678
Masukkan nilai ujian (0-100): 81

Nama: Sarah (type: <class 'str'>)
NIM: 12345678 (type: <class 'str'>)
Nilai: 81 (type: <class 'int'>)

Hasil Evaluasi:
Mahasiswa: Sarah (NIM: 12345678)
Nilai Ujian: 81
Kategori Nilai: B (Baik)
```

# **Input**
"""

Nama_Mahasiswa = "Sarah"
NIM = "12345678"
Nilai_Ujian = 81

A = "Sangat Baik"
B = "Baik"
C = "Cukup"
D = "Kurang"
E = "Sangat Kurang"

"""# **Output**"""

print(f"Nama: {Nama_Mahasiswa}")
print(f"NIM: {NIM}")
print(f"Nilai: {Nilai_Ujian}")

print(type(Nama_Mahasiswa))
print(type(NIM))
print(type(Nilai_Ujian))

"""# **Hasil Evaluasi**"""

Nilai_Ujian = 81

if 85 <= Nilai_Ujian <= 100:
    kategori = "A (Sangat Baik)"
elif 75 <= Nilai_Ujian <= 84:
    kategori = "B (Baik)"
elif 60 <= Nilai_Ujian <= 74:
    kategori = "C (Cukup)"
elif 40 <= Nilai_Ujian <= 59:
    kategori = "D (Kurang)"
else:
    kategori = "E (Sangat Kurang)"

print(f"Nilai Ujian: {Nilai_Ujian} -> Kategori: {kategori}")

print(f"Nama Mahasiswa: {Nama_Mahasiswa}")
print(f"Nilai Ujian: {Nilai_Ujian}")
print(f"Kategori Nilai: {kategori}")